repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.7" # Use the latest version
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.3.7"]

  - repo: local
    hooks:
      - id: test
        name: Unit Tests
        entry: npm run test
        language: system
        pass_filenames: false
        types: [javascript]
