repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.7"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.3.7"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        name: Prettier (Markdown)
        files: \.(md)$

  - repo: local
    hooks:
      - id: test
        name: Unit Tests
        entry: npm run test
        language: system
        pass_filenames: false
        types: [javascript]
